import streamlit as st
from groq import Groq

st.set_page_config(
    page_title="AI Content Assistant",
    page_icon="✍️",
    layout="wide"
)

# Get Groq API key from Streamlit Secrets
try:
    groq_api_key = st.secrets["GROQ_API_KEY"]
except Exception:
    groq_api_key = None

st.title("✍️ AI Content Assistant")
st.write(
    "Create platform-ready content using AI. "
    "Choose your content type, platform, audience and tone."
)

# Sidebar inputs
with st.sidebar:
    st.header("Content Settings")

    content_type = st.selectbox(
        "Content Type",
        [
            "LinkedIn Post",
            "Instagram Caption",
            "Facebook Post",
            "X / Twitter Post",
            "Blog Introduction",
            "Marketing Copy"
        ]
    )

    platform = st.selectbox(
        "Platform",
        [
            "LinkedIn",
            "Instagram",
            "Facebook",
            "X / Twitter",
            "Website / Blog"
        ]
    )

    tone = st.selectbox(
        "Tone",
        [
            "Professional",
            "Conversational",
            "Educational",
            "Inspirational",
            "Persuasive",
            "Thought Leadership",
            "Humorous"
        ]
    )

    st.divider()

    target_audience = st.text_input(
        "Target Audience",
        placeholder="e.g. Agile professionals, startup founders"
    )

    topic = st.text_area(
        "Topic",
        placeholder="What do you want to write about?",
        height=120
    )

    additional_context = st.text_area(
        "Additional Context (Optional)",
        placeholder="Add key points, facts, product information, experience, etc.",
        height=120
    )


def generate_content():
    prompt = f"""
You are an expert social media and content marketing writer.

Create high-quality original content based on the following requirements.

CONTENT TYPE:
{content_type}

PLATFORM:
{platform}

TOPIC:
{topic}

TARGET AUDIENCE:
{target_audience}

TONE:
{tone}

ADDITIONAL CONTEXT:
{additional_context}

Please produce the output in the following format:

### HOOK
Write a strong opening sentence that grabs attention.

### POST
Write the complete ready-to-publish post.

### CAPTION
Write a concise caption suitable for the selected platform.

### CALL TO ACTION
Write a natural call-to-action.

### HASHTAGS
Provide 8-12 relevant hashtags.

Requirements:
- Make the content original.
- Do not use generic AI-sounding language.
- Keep the writing natural and human.
- Match the selected platform.
- Match the selected audience.
- Match the requested tone.
- Do not invent statistics, research or facts.
- Do not mention that the content was generated by AI.
- Make the post ready to copy and publish.
"""

    client = Groq(api_key=groq_api_key)

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {
                "role": "system",
                "content": (
                    "You are an expert content strategist, "
                    "copywriter and social media writer."
                )
            },
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0.7,
        max_tokens=2000
    )

    return response.choices[0].message.content


if not groq_api_key:
    st.warning(
        "Groq API key not found. "
        "Please add GROQ_API_KEY to Streamlit Secrets."
    )
else:
    if st.button(
        "🚀 Generate Content",
        type="primary",
        use_container_width=True
    ):
        if not topic.strip():
            st.error("Please enter a topic first.")
        elif not target_audience.strip():
            st.error("Please enter your target audience.")
        else:
            with st.spinner("Creating your content..."):
                try:
                    generated_content = generate_content()
                    st.session_state["generated_content"] = generated_content
                except Exception as e:
                    st.error(
                        f"Something went wrong while generating content: {e}"
                    )

if "generated_content" in st.session_state:
    st.divider()
    st.subheader("✨ Generated Content")

    st.text_area(
        "Your Content",
        value=st.session_state["generated_content"],
        height=600
    )

    st.download_button(
        label="⬇️ Download Content",
        data=st.session_state["generated_content"],
        file_name="ai_generated_content.txt",
        mime="text/plain",
        use_container_width=True
    )
